apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: patrones-react
  name: patrones-react
  namespace: main
spec:
  selector:
    matchLabels:
      app: patrones-react
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: patrones-react
    spec:
      containers:
      - image: pipeba1408/patrones-react:050924
        name: patrones-react
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 40
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
